FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.23-openshift-4.19 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR "/build"

COPY . .

RUN if [ "$TARGETARCH" = "arm64" ] ; then \
        dnf update -y && \
        dnf install tar gawk gcc g++ git -y ; \
    fi

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.

# Due to https://github.com/golang/go/issues/70329 cross-compilation hangs at times.
# As a temporary workaround, we can try specifying GOMAXPROCS=2 to relieve this issue
RUN GOMAXPROCS=2 CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} make build-marvell-vsp

RUN if [ "$TARGETARCH" = "arm64" ] ; then \
        curl -L -O https://hyperrealm.github.io/libconfig/dist/libconfig-1.7.2.tar.gz && \
        tar -xvf libconfig-1.7.2.tar.gz && \
        cd libconfig-1.7.2 && \
        ./configure --prefix=/build/bin/ && \
        make && \
        make install ; \
    fi

RUN if [ "$TARGETARCH" = "arm64" ] ; then \
        git clone --depth=10 https://github.com/MarvellEmbeddedProcessors/pcie_ep_octeon_target.git && \
        cd "/build/pcie_ep_octeon_target/target/libs/octep_cp_lib" && \
        export CFLAGS="$CFLAGS -Wno-error=unused-result -DUSE_PEM_AND_DPI_PF=1" && \
        make ; \
    fi


RUN if [ "$TARGETARCH" = "arm64" ] ; then \
        cd "/build/pcie_ep_octeon_target/target/apps/octep_cp_agent" && \
        export OCTEP_PATH="/build/pcie_ep_octeon_target/target/libs/octep_cp_lib" && \
        export CFLAGS="$CFLAGS -I/build/bin/include -I$OCTEP_PATH/include" && \
        export LDFLAGS="-L/build/bin/lib -L$OCTEP_PATH" && \
        make ; \
    fi

# Use distroless as minimal base image to package the Marvell VSP binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM registry.ci.openshift.org/ocp/4.19:base-rhel9
ARG TARGETARCH

RUN dnf update -y && \
    dnf install \
       iproute \
       iputils \
       kmod \
       make \
       net-tools \
       pciutils \
       -y

COPY --from=builder /build /build

RUN if [ "$TARGETARCH" = "arm64" ] ; then \
        mv /build/bin/lib/libconfig* /usr/lib64/ && \
        mv /build/pcie_ep_octeon_target/target/apps/octep_cp_agent/cn106xx.cfg /usr/bin/ && \
        mv /build/pcie_ep_octeon_target/target/apps/octep_cp_agent/bin/bin/octep_cp_agent /usr/bin/ ; \
    fi && \
    mv /build/bin/vsp-mrvl.$TARGETARCH /vsp-mrvl && \
    mv /build/internal/daemon/vendor-specific-plugins/marvell/vsp-mrvl-run.sh / && \
    rm -rf /build/

USER 0

WORKDIR /

ENTRYPOINT [ ]
CMD [ "/vsp-mrvl-run.sh" ]
